@Cold Storage GO_HostAddress = https://localhost:7290

POST {{Cold Storage GO_HostAddress}}/test
Content-Type: application/json

{
    "title": "ASP.NET Core",
    "description": "My first web API"
}

###

POST https://localhost:7290/api/account/change-password
SessionId: 98fe291f-b0f9-4e7a-ae12-3166313c1f89
Content-Type: application/json

{
  "currentPassword": "stringst",
  "newPassword": "qwertyuiop",
  "confirmPassword": "qwertyuiop"
}


###
