@Cold Storage GO_HostAddress = https://localhost:7290

POST {{Cold Storage GO_HostAddress}}/test
Content-Type: application/json

{
    "title": "ASP.NET Core",
    "description": "My first web API"
}

###
